config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get '/about', to: 'about#index'

  
  
  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:new, :create, :destroy]
  resources :exercises
  resources :journal_entries, only: [:destroy, :index]

  # React API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :exercises, only: [ :index, :show, :create, :destroy, :show_random ]
      get 'exercise/random', to: 'exercises#show_random'
      resources :journal_entries, only: [ :new, :create, :index, :destroy ]
    end
  end
  
  # post '/session/new', to: 'home#session'
  match '*path', to: 'home#index', via: :all
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    user ||= User.new 

    if user.admin?
    
      can :manage, :all
  
    else
      can :read, :all
    end

    alias_action(:create, :read, :update, :delete, to: :crud)

    can(:crud, JournalEntry) do |journal_entry|
      user == journal_entry.user
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user

  has_many :favorite_exercises, dependent: :destroy
  has_many :fans, through: :favorite_exercises, source: :user

  validates :title, presence: true,
  uniqueness: { message: 'Title must be unique!'}
  validates :body, presence: true,
  length: { minimum: 10 }
end

app/models/favorite_exercise.rb
class FavoriteExercise < ApplicationRecord
  belongs_to :user
  belongs_to :exercise
end

app/models/favorite_video.rb
class FavoriteVideo < ApplicationRecord
  belongs_to :user
  belongs_to :video
end

app/models/journal_entry.rb
class JournalEntry < ApplicationRecord
  belongs_to :user

  validates :feeling, presence: { message: 'must select a value' },
            numericality: { only_integer: true }

  validates :body, presence: true,
            uniqueness: { message: 'has already been saved'},
            length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :exercises
  has_many :journal_entries, dependent: :destroy
  # Not adding a dependent nullify or destroy as only Admin's
  # will be able to add exercises. I don't want the exercises #disappearing even if the
  # associated admin is removed.

  has_many :favorite_exercises, dependent: :destroy
  has_many :favorited_exercises, through: :favorite_exercises, source: :exercise
  
  has_secure_password
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :username, presence: true,
                       uniqueness: true,
                       length: { minimum: 5}
  validates :email, presence: true,
                    uniqueness: true,
                    format: VALID_EMAIL_REGEX

  def full_name
    "#{first_name} #{last_name}".strip
  end
  
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery unless: -> { request.format.json? }

  private

  def current_user
    if session[:user_id].present?
      @current_user ||= User.find(session[:user_id])
    end
  end
  helper_method :current_user
  # by addinng the `helper_method` above 👆, we make this method available in
  # the view files. Normally, it's only available in controllers.

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def authenticate_user!
    unless user_signed_in?
      flash[:danger] = 'You must sign in or sign up first!'
      redirect_to new_sessions_path
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to main_app.root_url, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end


end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_exercise, only: [:show, :edit, :update, :destroy]
  
  
  def index
    @exercises = Exercise.all.order(created_at: :desc)
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = Exercise.new exercise_params
    @exercise.user = current_user

    if current_user.admin?
      @exercise.save
      redirect_to exercise_path(@exercise)
      flash[:success] = "You have created an exercise!"
    else
      render :new
      flash[:danger] = "You are not an admin!"
    end 
  end

  def edit

  end

  def update
    if @exercise.update exercise_params
      redirect_to exercise_path(@exercise)
    else
      render :edit
      flash[:danger] = "Exercise update failed"
    end
  end

  def show

  end

  private
  def find_exercise
    @exercise = Exercise.find params[:id]
  end

  def find_admin
    User.where({admin: :true})
  end

  def exercise_params
    params.require(:exercise).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email params[:email]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:danger] = 'Failed to Sign In'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'Thank you for signing up!'
      redirect_to root_path
    else
      #When user fails to sign up, the flash alert renders. But even when exited, if a user
      #goes to another page the flash alert will re-render. Low priority but needs fix
      flash[:danger] = "Failed to Sign Up"
      render :new
    end
  end

  def show
    @user = User.find params[:id]
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journal_entries_helper.rb
module JournalEntriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FeelBetter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all' %>

    <link href="home.scss" rel="stylesheet" type="scss">

    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    
    
  </head>

  <body>
    <div class="container" id="contentContainer">
    <header>
      <nav class="navbar navbar-fixed-top" id="navContainer">

        <div class="container-fluid" >
          <ul class="nav navbar-nav navbar-left" id="brandUl">
            <li id="brandLi">
              <a class="navbar-link navbar-left" id="brand" href="/">
                Feel Better
              </a>
            </li>
          </ul>
          
            
          <ul class="nav navbar-nav navbar-right" id="navRight">
            <% if user_signed_in? %>
              <li class="nav-item"> <%= link_to 'Journal', journal_entries_path %> </li>

            <% else %>
              <li class="nav-item"> <%= link_to 'Journal', journal_entries_path %> </li>
            <% end %>

            <% if user_signed_in? && current_user.admin? %>
              <li class="nav-item"> <%= link_to 'MHExercises', exercises_path %> </li>
              <li class="nav-item"> <%= link_to 'New MHExercise', new_exercise_path%> </li>
            <% end %>

            <% if user_signed_in? %>
              <li class="nav-item"> 
                <a> 
                  Hello <%= current_user.username %>! 
                </a>
              </li>
              <li class="nav-item"> <%= link_to 'Sign Out', sessions_path, method: :delete %></li>
            <% else %>
              <li class="nav-item"> <%= link_to 'Sign Up', new_user_path %> </li>
              <li class="nav-item"> <%= link_to 'Sign In', new_sessions_path %> </li>
            <% end %>
            <li class="nav-item"> <%= link_to 'About', about_path %> </li>
          </ul>
        </div>
      </nav>
    </header>

    <% flash.each do |type, message| %>
        <div id="alerts" class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
    <% end %>

    <%= yield %>
    </div>
  </body>
</html>